name: CI/CD Pipeline for building and publishing Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Copy the application.properties file
        run: cp ./src/main/resources/application.properties.example ./src/main/resources/application.properties
        shell: bash

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Test and Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push the docker image to Github Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/globex-trading/gt-data-fetcher-publisher:latest,ghcr.io/globex-trading/gt-data-fetcher-publisher:1.0.0

      - name: Dispatch the event to GT-Launcher for redeployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GT_LAUNCHER_REPOSITORY_DISPATCH_PAT }}
          repository: globex-trading/gt-launcher
          event-type: trigger-test-and-redeploy-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repo": "${{ github.repository }}"}'